export default {
  headers: [
    {
      field: 'id', //当sorted为true时，字段名用于传递到后台进行排序查询使用
      dataField: 'id',
      fieldName: '预约单号', //列表头名
      fixed: true, //true固定必须显示,false放到3个点中备用显示
      sorted: false, //true可以进行排序，false不可进行排序
      index: 1,
    },
    {
      field: 'education',
      dataField: 'education',
      fieldName: '预约项目',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'education',
      dataField: 'education',
      fieldName: '服务范围',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'worName',
      dataField: 'worName',
      fieldName: '护工姓名',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'gender',
      dataField: 'gender',
      fieldName: '护理对象',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'address',
      dataField: 'address',
      fieldName: '所在区域',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'addr',
      dataField: 'addr',
      fieldName: '详细地址',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'nurseId',
      dataField: 'nurseId',
      fieldName: '已付款',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'payType',
      dataField: 'payType',
      fieldName: '付款方式',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'zodiacType',
      dataField: 'zodiacType',
      fieldName: '售后类型',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'endTime',
      dataField: 'endTime',
      fieldName: '售后时间',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'state',
      dataField: 'state',
      fieldName: '状态',
      fixed: true,
      sorted: false,
      index: 1,
    },
  ],
  pages: 1,
  total: 13,
  pageNum: 1,
  pageSize: 10,
  list: [
    {
      index: 1,
      id: '14735AB83D5B4ECABBACA7DB03B0D1B7',
      nurseId: '45',
      pic: null,
      name: 'xxx',
      age: 0,
      gender: '赵游',
      gendersex: '男',
      address: 'HG123921',
      marital: '2020.12.01 00：00：00',
      education: '陪护',
      blood: 1757447848,
      constellation: '无',
      zodiac: '00255463',
      state: '启用',
      createTime: '2020-02-22T13:16:58.284+0000',
      userName: 22,
      phone: '15846589756',
      stateType: '1',
      genderType: '1',
      maritalType: '内科',
      educationType: 'PRIMARYSCHOOL',
      bloodType: 'BLOOD_A',
      constellationType: 'BAIYANG',
      zodiacType: '退款',
      business: '2020.12.01 00：00：00',
      endTime: '2020-02-22T13:16:58.284+0000',
      status: 5,
      worName: '周瑾',
      isStatuso: '已发布',
      money: '500.00',
      fee: '500.00',
      content: '陪护患者',
      addr: '2栋3楼',
      payType: '微信支付',
      state: '退款中',
    },
  ],
  prePage: 0,
  nextPage: 0,
}
