export default {
  headers: [
    {
      field: 'value', //当sorted为true时，字段名用于传递到后台进行排序查询使用
      dataField: 'value',
      fieldName: '评价', //列表头名
      fixed: true, //true固定必须显示,false放到3个点中备用显示
      sorted: false, //true可以进行排序，false不可进行排序
      index: 1,
    },
    {
      field: 'status',
      dataField: 'status',
      fieldName: '评分',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'xing',
      dataField: 'xing',
      fieldName: '满意度',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'gender',
      dataField: 'gender',
      fieldName: '用户',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'createTime',
      dataField: 'createTime',
      fieldName: '评价时间',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'id',
      dataField: 'id',
      fieldName: '预约单号',
      fixed: true,
      sorted: false,
      index: 1,
    },
  ],
  pages: 1,
  total: 13,
  pageNum: 1,
  pageSize: 10,
  list: [
    {
      index: 1,
      id: '14735AB83D5B4ECABBACA7DB03B0D1B7',
      nurseId: '45',
      pic: null,
      name: 'xxx',
      age: 0,
      gender: '赵游',
      gendersex: '男',
      address: 'HG123921',
      marital: '2020.12.01 00：00：00',
      education: '陪护',
      blood: 1757447848,
      constellation: '无',
      zodiac: '00255463',
      state: '启用',
      createTime: '2020-02-22T13:16:58.284+0000',
      userName: 22,
      phone: null,
      stateType: '1',
      genderType: '1',
      maritalType: null,
      educationType: 'PRIMARYSCHOOL',
      bloodType: 'BLOOD_A',
      constellationType: 'BAIYANG',
      zodiacType: null,
      business: '2020.12.01 00：00：00',
      endTime: '2020-02-22T13:16:58.284+0000',
      status: 5,
      worName: '周瑾',
      isStatuso: '已发布',
      value: '非常满意',
      xing: 5,
    },
  ],
  prePage: 0,
  nextPage: 0,
}
