export default {
  headers: [
    {
      field: 'index',
      dataField: 'index',
      fieldName: '序号',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'picId',
      dataField: 'picId',
      fieldName: '轮播图',
      fixed: true,
      sorted: false,
      index: 2,
    },

    {
      field: 'seq',
      dataField: 'seq',
      fieldName: '排序',
      fixed: true,
      sorted: false,
      index: 4,
    },
    {
      field: 'state',
      dataField: 'state',
      fieldName: '状态',
      fixed: true,
      sorted: false,
      index: 5,
    },
    {
      field: 'opt',
      dataField: 'opt',
      fieldName: '操作',
      fixed: true,
      sorted: false,
      index: 6,
    },
  ],
  pages: 1,
  total: 13,
  pageNum: 1,
  pageSize: 10,
  list: [
    {
      index: 1,
      id: 'B89DDC952F58438A9766F1453CA4BB89',
      picId: '8CE07C999D894331A6E9CB8966E946E3',
      links: '/pages-user/home/information/HospitalInformation',
      seq: 1,
      state: true,
      opt: null,
      linksType: 0,
    },
    {
      index: 2,
      id: '539081404A7A42DFA8E995CC5A82800B',
      picId: '8D2D4591BBA3494F8D5E185D7D5DED89',
      links: 'http://baijiahao.baidu.com/s?id=1693076525135208254',
      seq: 0,
      state: true,
      opt: null,
      linksType: 1,
    },
  ],
  prePage: 0,
  nextPage: 0,
}
