export default {
  headers: [
    {
      field: 'education',
      dataField: 'education',
      fieldName: '角色',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'gender',
      dataField: 'gender',
      fieldName: '使用账号',
      fixed: true,
      sorted: false,
      index: 1,
    },

    {
      field: 'userName',
      dataField: 'userName',
      fieldName: '状态',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'blood',
      dataField: 'blood',
      fieldName: '创建时间',
      fixed: true,
      sorted: false,
      index: 1,
    },
  ],
  pages: 1,
  total: 13,
  pageNum: 1,
  pageSize: 10,
  list: [
    {
      index: 1,
      id: '14735AB83D5B4ECABBACA7DB03B0D1B7',
      nurseId: 'ssd54654',
      pic: null,
      name: 'xxx',
      age: 0,
      gender: '0',
      gendersex: '外科一',
      address: 'zhaodeyuan',
      marital: '2020.12.01 00：00：00',
      education: '超级管理员',
      blood: '2020.12.01 00：00：00',
      constellation: '无',
      zodiac: '赵婷',
      state: '启用',
      createTime: '2020-02-22T13:16:58.284+0000',
      userName: '启用',
      phone: null,
      stateType: '1',
      genderType: '1',
      maritalType: null,
      educationType: 'PRIMARYSCHOOL',
      bloodType: 'BLOOD_A',
      constellationType: 'BAIYANG',
      zodiacType: null,
    },
    {
      index: 1,
      id: '14735AB83D5B4ECABBACA7DB03B0D1B7',
      nurseId: 'ssd54654',
      pic: null,
      name: 'xxx',
      age: 0,
      gender: '0',
      gendersex: '外科一',
      address: 'zhaodeyuan',
      marital: '2020.12.01 00：00：00',
      education: '客服专员',
      blood: '2020.12.01 00：00：00',
      constellation: '无',
      zodiac: '赵婷',
      state: '启用',
      createTime: '2020-02-22T13:16:58.284+0000',
      userName: '启用',
      phone: null,
      stateType: '1',
      genderType: '1',
      maritalType: null,
      educationType: 'PRIMARYSCHOOL',
      bloodType: 'BLOOD_A',
      constellationType: 'BAIYANG',
      zodiacType: null,
    },
  ],
  prePage: 0,
  nextPage: 0,
}
