export default {
  headers: [
    {
      field: 'index',
      dataField: 'index',
      fieldName: '序号',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'nickname',
      dataField: 'nickname',
      fieldName: '微信昵称',
      fixed: true,
      sorted: false,
      index: 2,
    },
    {
      field: 'userCode',
      dataField: 'userCode',
      fieldName: '用户ID',
      fixed: true,
      sorted: false,
      index: 3,
    },
    {
      field: 'payOpenId',
      dataField: 'payOpenId',
      fieldName: '微信openID',
      fixed: true,
      sorted: false,
      index: 4,
    },
    {
      field: 'patient_num',
      dataField: 'patientNum',
      fieldName: '性别',
      fixed: true,
      sorted: true,
      index: 5,
    },
    {
      field: 'fw_num',
      dataField: 'fwNum',
      fieldName: '所在地区',
      fixed: true,
      sorted: true,
      index: 6,
    },
    {
      field: 'first_login_time',
      dataField: 'firstLoginTime',
      fieldName: '第一次登录时间',
      fixed: true,
      sorted: true,
      index: 9,
    },
    {
      field: 'last_login_time',
      dataField: 'lastLoginTime',
      fieldName: '最近一次登录时间',
      fixed: true,
      sorted: true,
      index: 10,
    },
  ],
  pages: 2,
  total: 16,
  pageNum: 1,
  pageSize: 10,
  list: [
    {
      index: 1,
      id: '13EC2EE07A4746938595949CEA335BC5',
      avatar: '4D034281B6A14E01B38FB67E273CD1E8',
      nickname: null,
      userCode: '13EC2EE07A4746938595949CEA335BC5',
      payOpenId: 'oNiu_4gMOD66O_mShvvIVdmQB-VA',
      patientNum: '男',
      fwNum: '重庆市',
      cfNum: '0',
      payFee: '0.02',
      firstLoginTime: '2020-07-17 17:31:23',
      lastLoginTime: '2020-10-03 12:06:15',
    },
    {
      index: 2,
      id: '216FDD7280CD4935B96ECAA9927157BE',
      avatar: '60C5132B6598456E9713A20A2A7BABD1',
      nickname: '萤火虫',
      userCode: '216FDD7280CD4935B96ECAA9927157BE',
      payOpenId: 'oNiu_4nZl9N7HrN1AtJDcgNUbct0',
      patientNum: '女',
      fwNum: '重庆市',
      cfNum: '0',
      payFee: '0.18',
      firstLoginTime: '2020-07-17 17:32:02',
      lastLoginTime: '2021-01-21 15:54:30',
    },
  ],
  prePage: 0,
  nextPage: 2,
  extData: {},
}
