export default {
  headers: [
    {
      field: 'address', //当sorted为true时，字段名用于传递到后台进行排序查询使用
      dataField: 'address',
      fieldName: '编号', //列表头名
      fixed: true, //true固定必须显示,false放到3个点中备用显示
      sorted: false, //true可以进行排序，false不可进行排序
      index: 1,
    },
    {
      field: 'education',
      dataField: 'education',
      fieldName: '标题',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'gender',
      dataField: 'gender',
      fieldName: '业务',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'zodiac',
      dataField: 'zodiac',
      fieldName: '服务范围',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'nurseId',
      dataField: 'nurseId',
      fieldName: '分组',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'gendersex',
      dataField: 'gendersex',
      fieldName: '开始日期',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'userName',
      dataField: 'userName',
      fieldName: '结束日期',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'blood',
      dataField: 'blood',
      fieldName: '周期',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'business',
      dataField: 'business',
      fieldName: '状态',
      fixed: true,
      sorted: false,
      index: 1,
    },
    {
      field: 'status',
      dataField: 'status',
      fieldName: '创建时间',
      fixed: true,
      sorted: false,
      index: 1,
    },
  ],
  pages: 1,
  total: 13,
  pageNum: 1,
  pageSize: 10,
  list: [
    {
      index: 1,
      id: '14735AB83D5B4ECABBACA7DB03B0D1B7',
      nurseId: '分组一',
      pic: null,
      name: 'xxx',
      age: 0,
      gender: '陪护',
      gendersex: '2020.12.01 00：00：00',
      address: 'HG123921',
      marital: '2020.12.01 00：00：00',
      education: '陪护',
      blood: '每天',
      constellation: '无',
      zodiac: '1、2、3',
      state: '启用',
      createTime: '2020-02-22T13:16:58.284+0000',
      userName: '2020-02-22T13:16:58.284+0000',
      phone: null,
      stateType: '1',
      genderType: '1',
      maritalType: null,
      educationType: 'PRIMARYSCHOOL',
      bloodType: 'BLOOD_A',
      constellationType: 'BAIYANG',
      zodiacType: null,
      business: '待发布',
      status: '2020-02-22T13:16:58.284+0000',
      rmarks: '',
      goTime: '2020-02-22T13:16:58.284+0000',
      isstatus: '已执行',
      isEffect: false,
    },
    {
      index: 1,
      id: '14735AB83D5B4ECABBACA7DB03B0D1B7',
      nurseId: '分组二',
      pic: null,
      name: 'xxx',
      age: 0,
      gender: '送标',
      gendersex: '2020.12.01 00：00：00',
      address: 'H11235231',
      marital: '2020.12.01 00：00：00',
      education: '送标',
      blood: '每天',
      constellation: '无',
      zodiac: '1',
      state: '启用',
      createTime: '2020-02-22T13:16:58.284+0000',
      userName: '2020-02-22T13:16:58.284+0000',
      phone: null,
      stateType: '1',
      genderType: '1',
      maritalType: null,
      educationType: 'PRIMARYSCHOOL',
      bloodType: 'BLOOD_A',
      constellationType: 'BAIYANG',
      zodiacType: null,
      business: '生效中',
      status: '2020-02-22T13:16:58.284+0000',
      rmarks: '',
      goTime: '2020-02-22T13:16:58.284+0000',
      isstatus: '已执行',
      isEffect: true,
    },
  ],
  prePage: 0,
  nextPage: 0,
}
